version: '3.8'

services:
  postgres_development:
    image: postgres:15
    container_name: mentory_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mentory_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    container_name: mentory_postgres_test
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mentory_app_test
    ports:
      - "5888:5432"

volumes:
  pgdata: